name: Update Snapshots

on:
  issue_comment:
    types: [created]

jobs:
  updatesnapshots:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/update-snapshots'}}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get branch name
        id: branch_name
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.issue.number }},
            });
            return pullRequest.head.ref;
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch_name.outputs.result }}
      - name: Install Playwright chromium browser
        run: bash run.sh
